### ISSUE TITLE
Example in readme does not work in new SBT project with Scala 2.12.4

### ISSUE THREAD

**Issue by paulcarey** [circe/circe-config#16]
Using the `scala-seed.g8` template to create a new project, running the example in the readme fails with the following compiler errors:

    object generic is not a member of package io.circe
    [error]   import io.circe.generic.auto._

    could not find implicit value for evidence parameter of type io.circe.Decoder[foo.ServerSettings
    [error]     val x = c.as[ServerSettings]("http.server")

`circe-generic` is a `Test` dependency, which I think it should not be.

**Comment by paulcarey** [comment]
I created a project via `sbt new sbt/scala-seed.g8`.

But why is `circe-generic` listed as a test dependency in `build.sbt`?

**Comment by jonas** [comment]
It is listed as a test dependency because it is run as part of the
test suite using sbt-doctest.

**Comment by paulcarey** [comment]
Ok, thanks. Maybe I'm missing something, but then I think either:

* The readme should be updated to state that `circe-generic` should be added to `libraryDependencies`, or
* The `test` classification should be dropped, so `circe-generic` would become a transitive dependency.

**Comment by jonas** [comment]
I agree. Let me know if you are interested in cooking up a PR to update the
README.

>
